# version: '4.41.2'

services:
  db:
    image: postgres:17.5 # o la version postgres:latest
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data